
project_id = "fkagpyfzgczcaxsqwsoi"

# Enable JWT verification for protected functions by default
[functions]
verify_jwt = true

# Allow public access to our arbitrage scanning functions
[functions.update-price-data]
verify_jwt = false

[functions.scan-arbitrage]
verify_jwt = false
