
project_id = "fkagpyfzgczcaxsqwsoi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions.real-time-prices]
verify_jwt = false

[functions.execute-trade]
verify_jwt = false
